# Generated by Django 4.1 on 2022-10-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_remove_monthlycontribution_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlycontribution',
            old_name='receipt_ID',
            new_name='receiptID',
        ),
        migrations.RenameField(
            model_name='monthlycontribution',
            old_name='reg_number',
            new_name='regnumber',
        ),
    ]
