# Generated by Django 4.1 on 2022-10-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_rename_receipt_id_monthlycontribution_receiptid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlycontribution',
            old_name='receiptID',
            new_name='receipt_ID',
        ),
        migrations.RenameField(
            model_name='monthlycontribution',
            old_name='regnumber',
            new_name='reg_number',
        ),
    ]
