# Generated by Django 4.1 on 2022-10-21 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0004_rename_receiptid_monthlycontribution_receipt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerryGoRoundContribution',
            fields=[
                ('receipt_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(default=0)),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
