# Generated by Django 4.1 on 2022-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_merrygoroundcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='merrygoroundcontribution',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
