# Generated by Django 4.1 on 2022-10-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_merrygoroundcontribution_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlycontribution',
            old_name='receipt_ID',
            new_name='id',
        ),
    ]
