# Generated by Django 4.1 on 2022-10-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_rename_receipt_id_monthlycontribution_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merrygoroundcontribution',
            old_name='receipt_ID',
            new_name='id',
        ),
    ]
