# Generated by Django 4.1 on 2022-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_rename_receipt_id_merrygoroundcontribution_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merrygoroundcontribution',
            old_name='date_joined',
            new_name='date_contributed',
        ),
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='date_contributed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
