# Generated by Django 4.1 on 2022-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_rename_date_joined_merrygoroundcontribution_date_contributed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merrygoroundcontribution',
            name='date_contributed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycontribution',
            name='date_contributed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
