# Generated by Django 4.1 on 2022-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
