# Generated by Django 4.1 on 2022-10-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_number',
            new_name='regnumber',
        ),
    ]
