# Generated by Django 4.1 on 2022-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_nextofkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ict',
            field=models.BooleanField(default=False),
        ),
    ]
