# Generated by Django 4.1 on 2022-10-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_ict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ict',
        ),
    ]
