# Generated by Django 4.1 on 2022-10-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_regnumber_user_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_number',
            new_name='id',
        ),
    ]
