# Generated by Django 4.1 on 2022-12-07 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('loan_type', models.TextField(choices=[('ElimuLoan', 'Elimu Loan'), ('AssetLoan', 'Asset Loan'), ('PersonalLoan', 'Personal Loan')], default='Pending')),
                ('amount_requested', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending')),
                ('date_requested', models.DateField(auto_now_add=True, null=True)),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Request',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('payment_id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequest')),
            ],
        ),
    ]
