# Generated by Django 4.1 on 2023-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
