# Generated by Django 4.1 on 2023-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loancategory_remove_loanrequest_loan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
