# Generated by Django 4.1 on 2023-01-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrequest_purpose_loanrequest_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='year',
        ),
    ]
