# Generated by Django 4.1 on 2023-02-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloan',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequest'),
        ),
    ]
