# Generated by Django 4.1 on 2023-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanrequest_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='payment_period_years',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
