# Generated by Django 4.1 on 2022-10-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_nextofkin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
