# Generated by Django 4.1 on 2022-10-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextOfKin',
        ),
    ]
